project:
  pre-render: quarto convert index.qmd
execute:
  eval: true
  echo: true
  output: true
  warning: true
  error: true
  freeze: false
  cache: false
  enabled: true
html:
  other-links:
    - text: Jupyter Notebook
      href: index.ipynb