on:
  workflow_dispatch:
  push:
    branches: main

env:
  QUARTO_PROFILE: ci

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    container:
      image: ${{ secrets.DOCKERHUB_USERNAME }}/rdm-bids:latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUARTO_PROFILE: ci
          QUARTO_PYTHON: /app/.venv/bin/python
        with:
          target: gh-pages

